cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

favorite/urls.py
# favorite/urls.py
from django.urls import path
from . import views

app_name = 'favorite'

urlpatterns = [
    path('product/<int:product_id>/add/', views.add_to_favorites, name='add_to_favorites'),
    path('product/<int:product_id>/remove/', views.remove_from_favorites, name='remove_from_favorites'),
    path('favorites/', views.favorite_list, name='favorite_list'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('favorite/', include('favorite.urls', namespace='favorite')),
    path('reports/', include('reports.urls', namespace='reports')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('cart/', views.cart, name='cart'),

    path('ayuda/', views.ayuda, name='ayuda'),

    path('quienes_somos/', views.quienes_somos, name='quienes_somos'),

    path('politica_privacidad/', views.politica_privacidad, name='politica_privacidad'),

    path('tyc/', views.tyc, name='tyc'),
    
    path('blog/', views.blog, name='blog'),


    path('', views.product_list, name='product_list'),
    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category'
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail'
    ),
    path('search/', views.search_products, name='search_products'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Promocion(models.Model):
    nombre = models.CharField(max_length=200)
    descuento = models.DecimalField(max_digits=5, decimal_places=2)  # Porcentaje de descuento
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()

    def __str__(self):
        return self.nombre

    @property
    def is_active(self):
        today = timezone.now().date()
        return self.fecha_inicio <= today <= self.fecha_fin


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    promocion = models.ForeignKey(Promocion, related_name='productos', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    @property
    def precio_con_descuento(self):
        if self.promocion and self.promocion.is_active:
            return self.price * (1 - (self.promocion.descuento / 100))
        return self.price

shop/views.py
from django.shortcuts import get_object_or_404, render
from django.db.models import Q
from cart.forms import CartAddProductForm
from .models import Category, Product
from django.http import HttpResponse
from django.utils import timezone

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    search_query = request.GET.get('q', '') # Busqueda 

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    if search_query:# Busqueda
        products = products.filter(
            Q(name__icontains=search_query) | Q(description__icontains=search_query)
        )

    no_products = not products and search_query # Busqueda

    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
            'cart_product_form': cart_product_form,  
        },
    )

def cart(request):
    return render(request, 'cart/detail.html')

def product_detail(request, id, slug):
    product = get_object_or_404(
        Product, id=id, slug=slug, available=True
    )
    cart_product_form = CartAddProductForm()
    return render(
        request,
        'shop/product/detail.html',
        {'product': product, 'cart_product_form': cart_product_form},
    )

# Vista para buscar productos
def search_products(request):
    query = request.GET.get('q', '')  # Obtener la consulta de búsqueda del usuario
    results = Product.objects.filter(name__icontains=query, available=True)  # Filtrar productos disponibles por nombre
    return render(request, 'shop/search_results.html', {'products': results, 'query': query})

def ayuda(request):
    return render(request, 'info/ayuda.html')

def quienes_somos(request):
    return render(request, 'info/quienes_somos.html')

def politica_privacidad(request):
    return render(request, 'info/politica_privacidad.html')

def tyc(request):
    return render(request, 'info/terminos_condiciones.html')

def blog(request):
    return render(request, 'info/blog.html')



   

shop/templates/shop/product/detail.html
{% extends "shop/base_nav.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}

<div class="container d-flex justify-content-center mt-5">
    <div class="card" style="width: 70rem;">
      <div class="card-body">
        <div class="row" style="color: #4E50B4;">
  
          <div class="col">
            <h2 style="color: #4E50B4;" class="mb-3"><strong>{{ product.name }}</strong></h2>
            <p class="price fw-bold" style="color: #4E50B4; margin-bottom: 2px;">Precio:</p>
            <p>${{ product.price }}</p>
            <p class="price fw-bold" style="color: #4E50B4;">Descripción:</p>
            <p style="margin-top: -15px;">{{ product.description|linebreaks }}</p>
  
            <div class="d-flex">
              <form action="{% url 'cart:cart_add' product.id %}" method="post" class="me-3">
                {% csrf_token %}
                <input type="hidden" name="quantity" value="1">
                <button type="submit" class="btn" style="background-color: #34DD78; width: 60px; height: 60px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: auto;" aria-label="Agregar al carrito">
                  <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="#4E50B4" class="bi bi-cart4" viewBox="0 0 16 16">
                    <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
                  </svg>
                </button>
              </form>
            
              {% if user.is_authenticated %}
                {% if is_favorite %}
                  <form action="{% url 'favorite:remove_from_favorites' product.id %}" method="post" class="me-3">
                    {% csrf_token %}
                    <input type="submit" value="Remove from Favorites" aria-label="Eliminar de favoritos">
                  </form>
                {% else %}
                  <form action="{% url 'favorite:add_to_favorites' product.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn" style="background-color: #4E50B4; width: 60px; height: 60px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: auto;" aria-label="Agregar a favoritos">
                      <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="#FFFFFF" class="bi bi-heart" viewBox="0 0 16 16">
                        <path d="M8 3.314C12.438-1.248 23.534 4.735 8 15-7.534 4.736 3.562-1.248 8 3.314z"/>
                      </svg>
                    </button>
                  </form>
                {% endif %}
              {% endif %}
            </div>
          </div>
  
          <div class="col">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="img-fluid" style="height: 250px;">
          </div>
        </div>
  
      </div>
    </div>
</div>

{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Productos{% endif %}
{% endblock %}

{% block content %}

<!-- Categorias -->
<nav class="category-nav mb-3">
  <ul class="nav" style="background-color: #9394D5;">
    {% for c in categories %}
    <li class="nav-item">
      <a class="nav-link {% if category.slug == c.slug %}selected{% endif %} fw-bold" href="{{ c.get_absolute_url }}"
        style="color: #E7F1F6;">{{ c.name }}</a>
    </li>
    {% endfor %}
  </ul>
</nav>
<!-- Categorias -->

<!-- Contenedor para mensajes -->
<div id="message" class="alert alert-success" style="display: none;"></div>



<h2 class="text-center fw-bold" style="color: #4E50B4;">
  {% if category %}{{ category.name }}{% else %} Productos destacados {% endif %}
</h2>

<!-- Card de cada producto -->
<div class="container mt-5 mb-5">
  <div class="row g-3 justify-content-center"> 
    {% if products %}
      {% for product in products %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 d-flex justify-content-center">
          <div class="card product-card" style="background-color: #E7F1F6; border: none; height: 500px;">
            <a href="{{ product.get_absolute_url }}" class="d-flex justify-content-center">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"
                class="card-img-top img-thumbnail" alt="{{ product.name }}" style="max-width: 190px; max-height: 190px; margin-top: 15px;">
            </a>
            <div class="card-body text-center">
              <p class="card-title fw-bold">
                <a href="{{ product.get_absolute_url }}" class="text-decoration-none" style="color: #4E50B4;">{{ product.name }}</a>
              </p>
              
              <p class="card-text fw-semibold" style="color: #4E50B4;">
                {% if product.promocion and product.promocion.is_active %}
                    <span style="text-decoration: line-through; color: #FF0000;">Precio original: ${{ product.price }}</span><br>
                    <strong>Precio con descuento: ${{ product.precio_con_descuento|floatformat:2 }}</strong><br>
                    <span style="color: #28A745;">(Descuento: {{ product.promocion.descuento }}%)</span>
                {% else %}
                    Precio: ${{ product.price }}
                {% endif %}
              </p>            

              <div class="d-flex justify-content-center align-items-center mt-4">

                <form action="{% url 'cart:cart_add' product.id %}" method="post" class="add-to-cart-form me-2">
                  {% csrf_token %}
                  <input type="hidden" name="quantity" value="1"> <!-- Cantidad fija -->
                  <button type="submit" class="btn" style="background-color: #34DD78; width: 60px; height: 60px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: auto;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="#4E50B4" class="bi bi-cart4" viewBox="0 0 16 16">
                      <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
                    </svg>
                  </button>
                </form>
              
  
                <form action="{% url 'favorite:add_to_favorites' product.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit"  value="agregar a favoritos" class="btn" style="background-color: #4E50B4; width: 60px; height: 60px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: auto;">
                      <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="#FFFFFF" class="bi bi-heart" viewBox="0 0 16 16">
                          <path d="M8 3.314C12.438-1.248 23.534 4.735 8 15-7.534 4.736 3.562-1.248 8 3.314z"/>
                      </svg>
                  </button>
                </form>
              </div> 
              
            </div>
          </div>
        </div>
      {% endfor %}
    <!-- Mensaje de busqueda-->
    {% else %}
      <div class="alert alert-warning text-center mt-3" style="width: 100%;">
        No se encontraron resultados para tu búsqueda.
      </div>
    {% endif %}
    <!-- Mensaje de busqueda-->
  </div>
</div>

<!-- Card de cada producto -->

<!-- Footer-->
<footer class="row">

  <div class="col p-3 ps-4" style="background-color: #a9a9dd;">
    <div class="card" style="width: 18rem; background-color: #e7f1f6;">
      <div class="card-body fw-bold text-start">
        <p class="card-text">
          <a href="#" style="color: #4e50b4; text-decoration: none;">
            <img src="{% static 'img/footer/ayuda.png' %}" alt="icon_help" width="20px"> Ayuda
          </a>
        </p>
        <p>
          <a href="#" style="color: #4e50b4; text-decoration: none;">
            <img src="{% static 'img/footer/quienes _somos.png' %}" alt="icon_quien_somos" width="20px"> Quienes somos
          </a>
        </p>
        <p>
          <a href="#" style="color: #4e50b4; text-decoration: none;">
            <img src="{% static 'img/footer/politicas_privacidad.png' %}" alt="icon_PdP" width="20px"> Políticas de Privacidad
          </a>
        </p>
        <p>
          <a href="#" style="color: #4e50b4; text-decoration: none;">
            <img src="{% static 'img/footer/terminos-y-condiciones.png' %}" alt="icon_TyC" width="20px"> Términos y Condiciones
          </a>
        </p>
        <p>
          <a href="{% url 'shop:blog' %}" style="color: #4e50b4; text-decoration: none;">
            <img src="{% static 'img/footer/blog.png' %}" alt="icon_blog" width="20px"> Blog
          </a>
        </p>
      </div>
    </div>
  </div>

  <div class="col p-3" style="background-color: #a9a9dd;">
    <h5 style="color: white;" class="fw-bold mb-4">Contactos</h5>
    <div class="d-flex flex-column">
      <a style="color: white; text-decoration: none;" class="fw-semibold mb-3">
        <img src="{% static 'img/footer/whatsapp.png' %}" alt="logo_Whatsapp" width="30px">3126647917
      </a>
      <a href="" style="color: white; text-decoration: none;" class="fw-semibold">
        <img src="{% static 'img/footer/gmail.png' %}" alt="" width="30px"> v-pharma@gmail.com
      </a>
    </div>
  </div>

  <div class="col p-3" style="background-color: #a9a9dd;">
    <h5 style="color: white;" class="fw-bold mb-4">Síguenos</h5>
    <div class="d-flex flex-column">
      <a href="" style="color: white; text-decoration: none;" class="fw-semibold mb-3">
        <img src="{% static 'img/footer/instagram.png' %}" alt="logo_ig" width="30px"> V-Pharma Oficial
      </a>
      <a href="" style="color: white; text-decoration: none;" class="fw-semibold">
        <img src="{% static 'img/footer/facebook.png' %}" alt="logo_facebook" width="30px"> V-Pharma
      </a>
    </div>
  </div>

</footer>
<!-- Footer -->


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('.add-to-cart-form').on('submit', function(e) {
            e.preventDefault(); // Evitar el envío normal del formulario

            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function(response) {
                    // Mostrar un mensaje de éxito al usuario
                    $('#message').text('Su producto se ha añadido al carrito correctamente.').show().fadeOut(3000);
                },
                error: function(xhr, errmsg, err) {
                    // Mostrar un mensaje de error al usuario
                    $('#message').text('Error al añadir al carrito').show().fadeOut(3000);
                }
            });
        });
    });
</script>



{% endblock %}