cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('favorite/', include('favorite.urls', namespace='favorite')),
    path('reports/', include('reports.urls', namespace='reports')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order/<int:order_id>/', views.order_created, name='order_created'),
    path('order/<int:order_id>/invoice/', views.generate_invoice_pdf, name='order_invoice'),
]

orders/models.py
from django.db import models

# Create your models here.


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        related_name='items',
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        'shop.Product',
        related_name='order_items',
        on_delete=models.CASCADE
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms

from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name',
            'last_name',
            'email',
            'address',
            'postal_code',
            'city',
        ]

orders/views.py
# views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from cart.cart import Cart
from .forms import OrderCreateForm
from .models import Order, OrderItem
from .utils import create_invoice_pdf  # Cambia el nombre aquí

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user if request.user.is_authenticated else None
            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity'],
                )
            cart.clear()
            return redirect(reverse('orders:order_created', kwargs={'order_id': order.id}))
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})

def order_created(request, order_id):
    try:
        order = Order.objects.get(id=order_id)
    except Order.DoesNotExist:
        return render(request, 'orders/order/404.html', status=404)
    
    return render(request, 'orders/order/created.html', {'order': order})

def generate_invoice_pdf(request, order_id):
    return create_invoice_pdf(order_id)  # Cambia el nombre aquí

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
  Checkout
{% endblock %}

{% block content %}

<div class="container">
  <div class="row ">
      <div class="col-md-10 align-items-center">
      <h1 class="" style="color: #a9a9dd;"><strong>Verificar</strong></h1><br>
        <form method="post" class="order-form">
          {{ form.as_p }}
          <p><input type="submit" value="Place order" style="background-color: #a9a9dd;;"></p>
          {% csrf_token %}
        </form>
    </div>
    <div class="col-md-2 order-info ">
      <h3>Tu Pedido</h3>
      <ul>
        {% for item in cart %}
          <li>
            {{ item.quantity }}x {{ item.product.name }}
            <span>${{ item.total_price }}</span>
          </li>
        {% endfor %}
      </ul>
      <p>Total: ${{ cart.get_total_price }}</p>
    </div>
  </div>
</div>
  
 
  
{% endblock %}

orders/templates/orders/order/created.html
  <!-- templates/orders/order/created.html -->
{% extends "shop/base.html" %}
{% block title %}
  Thank you
{% endblock %}
<div class="d-flex align-items-center justify-content-center"></div>

{% block content %}
<div class="container d-flex justify-content-center align-items-center mt-5 pt-5">
  <div class="row ">
    <div class="col">
      <h1 style="color: #4E50B4;"><strong>Gracias!</strong></h1>
      <p>Su pedido se ha completado con éxito. Su número de pedido es
      <strong style="color: #4E50B4;">{{ order.id }}</strong>.</p>
      <p><a href="{% url 'orders:order_invoice' order.id %}" class="btn btn-primary d-flex justify-content-center" style="background-color: #9394D5; border: none;">Descarga tu factura en PDF</a></p>
    </div>
  </div>
</div>

{% endblock %}

orders/templates/orders/order/invoice.html
<!-- templates/orders/order/invoice.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>factura {{ order.id }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 1in;
        }
        h1 {
            text-align: center;
        }
        .order-details {
            margin-top: 1in;
        }
        .order-details ul {
            list-style-type: none;
            padding: 0;
        }
        .order-details li {
            margin-bottom: 0.5em;
        }
    </style>
</head>
<body>
    <h1>Factura #{{ order.id }}</h1>
    <p>fecha: {{ order.created_at.strftime('%Y-%m-%d') }}</p>
    
    <div class="order-details">
        <h2>Detalles del pedido:</h2>
        <ul>
            {% for item in order.items.all %}
            <li>
                {{ item.quantity }}x {{ item.product.name }} - ${{ item.price }}
            </li>
            {% endfor %}
        </ul>
        <p>Total: ${{ order.get_total_price }}</p>
    </div>
</body>
</html>