cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

favorite/urls.py
# favorite/urls.py
from django.urls import path
from . import views

app_name = 'favorite'

urlpatterns = [
    path('product/<int:product_id>/add/', views.add_to_favorites, name='add_to_favorites'),
    path('product/<int:product_id>/remove/', views.remove_from_favorites, name='remove_from_favorites'),
    path('favorites/', views.favorite_list, name='favorite_list'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('favorite/', include('favorite.urls', namespace='favorite')),
    path('reports/', include('reports.urls', namespace='reports')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('cart/', views.cart, name='cart'),

    path('ayuda/', views.ayuda, name='ayuda'),

    path('quienes_somos/', views.quienes_somos, name='quienes_somos'),

    path('politica_privacidad/', views.politica_privacidad, name='politica_privacidad'),

    path('tyc/', views.tyc, name='tyc'),
    
    path('blog/', views.blog, name='blog'),


    path('', views.product_list, name='product_list'),
    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category'
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail'
    ),
    path('search/', views.search_products, name='search_products'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Promocion(models.Model):
    nombre = models.CharField(max_length=200)
    descuento = models.DecimalField(max_digits=5, decimal_places=2)  # Porcentaje de descuento
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()

    def __str__(self):
        return self.nombre

    @property
    def is_active(self):
        today = timezone.now().date()
        return self.fecha_inicio <= today <= self.fecha_fin


class Product(models.Model):
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    promocion = models.ForeignKey(Promocion, related_name='productos', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    @property
    def precio_con_descuento(self):
        if self.promocion and self.promocion.is_active:
            return self.price * (1 - (self.promocion.descuento / 100))
        return self.price

shop/views.py
from django.shortcuts import get_object_or_404, render
from django.db.models import Q
from cart.forms import CartAddProductForm
from .models import Category, Product
from django.http import HttpResponse
from django.utils import timezone

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    cart_product_form = CartAddProductForm()
    search_query = request.GET.get('q', '') # Busqueda 

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    if search_query:# Busqueda
        products = products.filter(
            Q(name__icontains=search_query) | Q(description__icontains=search_query)
        )

    no_products = not products and search_query # Busqueda

    return render(
        request,
        'shop/product/list.html',
        {
            'category': category,
            'categories': categories,
            'products': products,
            'cart_product_form': cart_product_form,  
        },
    )

def cart(request):
    return render(request, 'cart/detail.html')

def product_detail(request, id, slug):
    product = get_object_or_404(
        Product, id=id, slug=slug, available=True
    )
    cart_product_form = CartAddProductForm()
    return render(
        request,
        'shop/product/detail.html',
        {'product': product, 'cart_product_form': cart_product_form},
    )

# Vista para buscar productos
def search_products(request):
    query = request.GET.get('q', '')  # Obtener la consulta de búsqueda del usuario
    results = Product.objects.filter(name__icontains=query, available=True)  # Filtrar productos disponibles por nombre
    return render(request, 'shop/search_results.html', {'products': results, 'query': query})

def ayuda(request):
    return render(request, 'info/ayuda.html')

def quienes_somos(request):
    return render(request, 'info/quienes_somos.html')

def politica_privacidad(request):
    return render(request, 'info/politica_privacidad.html')

def tyc(request):
    return render(request, 'info/terminos_condiciones.html')

def blog(request):
    return render(request, 'info/blog.html')



   

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>{% block title %}v-Pharma{% endblock %}</title>
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>

  <!-- NavBar -->
  <nav class="navbar navbar-expand-lg" style="background-color: #34DD78; margin: 0; padding: 0;">
    <div class="container-fluid " style="padding: 0;">
      <a class="navbar-brand fw-bold me-5" href="{% url 'shop:product_list' %}" style="color: #4E50B4; font-family: 'Poppins', sans-serif;">
        <img src="{% static 'img/logo_v-pharma.png' %}" alt="logo" width="50" class="me-1">
        V-Pharma
      </a>

      <!-- Busqueda -->
      <form class="d-flex" role="search" method="get" action="{% url 'shop:product_list' %}">
        <button class="btn me-2" type="submit" style="background-color: #4E50B4;">
          <img src="{% static 'img/lupa.png' %}" alt="Buscar" width="20">
        </button>
        <input class="form-control form" type="search" placeholder="¿Qué Buscas?" name="q" value="{{ search_query }}" aria-label="Search">
      </form>
      <!-- Busqueda -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ms-auto d-flex align-items-center">

          <li class="nav-item dropdown me-3" style="list-style: none;">
            <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="#4E50B4" class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
              </svg>
            </a>
            <ul class="dropdown-menu text-center" style="background-color: #E7F1F6;">
              {% if user.is_authenticated %}
                <li><a class="dropdown-item fw-semibold" href="{% url 'perfil' %}" style="color: #4E50B4;">{% if user.is_superuser %}Perfil de administrador{% else %}Perfil de usuario{% endif %}</a></li>
                <li>
                  <form action="{% url 'logout' %}" method="post" style="display: inline;">
                      {% csrf_token %}
                      <button type="submit" class="dropdown-item fw-semibold" style="color: #4E50B4;">Cerrar sesión</button>
                  </form>
                </li>
              {% else %}
                <li><a class="dropdown-item fw-semibold" href="{% url 'login' %}" style="color: #4E50B4;">Iniciar sesión</a></li>
                <li><a class="dropdown-item fw-semibold" href="{% url 'register' %}" style="color: #4E50B4;">Registrarse</a></li>
              {% endif %}
            </ul>
          </li>

          <div style="position: relative;" class="me-3">
            {% with total_items=cart|length %}
            <a href="{% url 'cart:cart_detail' %}" class="carrito">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="#4E50B4" class="bi bi-cart4" viewBox="0 0 16 16">
                <path
                  d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0" />
              </svg>
              <span class="badge bg-light text-dark position-absolute top-0 start-100 translate-middle rounded-pill">
                {{ total_items }}
              </span>
            </a>
            {% endwith %}
          </div>
          
          <a class="me-3" href="{% url 'favorite:favorite_list' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="currentColor" class="bi bi-bookmark-star-fill"
              viewBox="0 0 16 16" style="color: #4E50B4;">
              <path fill-rule="evenodd"
                d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5M8.16 4.1a.178.178 0 0 0-.32 0l-.634 1.285a.18.18 0 0 1-.134.098l-1.42.206a.178.178 0 0 0-.098.303L6.58 6.993c.042.041.061.1.051.158L6.39 8.565a.178.178 0 0 0 .258.187l1.27-.668a.18.18 0 0 1 .165 0l1.27.668a.178.178 0 0 0 .257-.187L9.368 7.15a.18.18 0 0 1 .05-.158l1.028-1.001a.178.178 0 0 0-.098-.303l-1.42-.206a.18.18 0 0 1-.134-.098z" />
            </svg>
          </a>

        </div>
      </div>
    </div>
  </nav>
  <!-- NavBar -->

   <!-- Mensajes -->
  {% if messages %}
   <div class="messages">
     {% for message in messages %}
       <div class="alert alert-{{ message.tags }}">
         {{ message }}
       </div>
     {% endfor %}
   </div>
 {% endif %}

 <div id="row">
   {% block content %}
   {% endblock %}
 </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/base_nav.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>{% block title %}v-Pharma{% endblock %}</title>
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>

  <!-- NavBar -->
  <nav class="navbar navbar-expand-lg" style="background-color: #34DD78; margin: 0; padding: 0; height: 70px;">
    <div class="container-fluid " style="padding: 0;">
      <div class="btn">
        <a href="{% url 'shop:product_list' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="35" fill="#4E50B4" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
            </svg>
        </a>
      </div>
     
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ms-auto d-flex align-items-center">

          <li class="nav-item dropdown me-3" style="list-style: none;">
            <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="#4E50B4" class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
              </svg>
            </a>
            <ul class="dropdown-menu text-center" style="background-color: #E7F1F6;">
              {% if user.is_authenticated %}
                <li><a class="dropdown-item fw-semibold" href="{% url 'perfil' %}" style="color: #4E50B4;">{% if user.is_superuser %}Perfil de administrador{% else %}Perfil de usuario{% endif %}</a></li>
                <li>
                  <form action="{% url 'logout' %}" method="post" style="display: inline;">
                      {% csrf_token %}
                      <button type="submit" class="dropdown-item fw-semibold" style="color: #4E50B4;">Cerrar sesión</button>
                  </form>
                </li>
              {% else %}
                <li><a class="dropdown-item fw-semibold" href="{% url 'login' %}" style="color: #4E50B4;">Iniciar sesión</a></li>
                <li><a class="dropdown-item fw-semibold" href="{% url 'register' %}" style="color: #4E50B4;">Registrarse</a></li>
              {% endif %}
            </ul>
          </li>

          <div style="position: relative;" class="me-3">
            {% with total_items=cart|length %}
            <a href="{% url 'cart:cart_detail' %}" class="carrito">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="#4E50B4" class="bi bi-cart4" viewBox="0 0 16 16">
                <path
                  d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0" />
              </svg>
              <span class="badge bg-light text-dark position-absolute top-0 start-100 translate-middle rounded-pill">
                {{ total_items }}
              </span>
            </a>
            {% endwith %}
          </div>
          
          <a class="me-3" href="{% url 'favorite:favorite_list' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" fill="currentColor" class="bi bi-bookmark-star-fill"
              viewBox="0 0 16 16" style="color: #4E50B4;">
              <path fill-rule="evenodd"
                d="M2 15.5V2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5M8.16 4.1a.178.178 0 0 0-.32 0l-.634 1.285a.18.18 0 0 1-.134.098l-1.42.206a.178.178 0 0 0-.098.303L6.58 6.993c.042.041.061.1.051.158L6.39 8.565a.178.178 0 0 0 .258.187l1.27-.668a.18.18 0 0 1 .165 0l1.27.668a.178.178 0 0 0 .257-.187L9.368 7.15a.18.18 0 0 1 .05-.158l1.028-1.001a.178.178 0 0 0-.098-.303l-1.42-.206a.18.18 0 0 1-.134-.098z" />
            </svg>
          </a>

        </div>
      </div>
    </div>
  </nav>
  <!-- NavBar -->

   <!-- Mensajes -->
  {% if messages %}
   <div class="messages">
     {% for message in messages %}
       <div class="alert alert-{{ message.tags }}">
         {{ message }}
       </div>
     {% endfor %}
   </div>
 {% endif %}

 <div id="row">
   {% block content %}
   {% endblock %}
 </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/search_results.html
<h2>Resultados para "{{ query }}"</h2>

{% if results %}
    <ul>
    {% for product in results %}
        <li>
            <a href="{% url 'product_detail' product.id %}">{{ product.name }}</a> - {{ product.price }} $
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No se encontraron resultados.</p>
{% endif %}